Improve README with pagination information
meilisearch/instant-meilisearch pull request #120
Opened 2020-11-05 14:04 UTC by curquiza

2020-11-05 14:09 UTC, curquiza commented
bors try

2020-11-05 17:29 UTC, bidoubiwa requested changes

2020-11-05 17:29 UTC, bidoubiwa commented on README.md
> +It means, by default, you can browse `paginationTotalHits / hitsPerPage = 200 / 20 = 10` pages during pagination.<br>
```suggestion
Which means that, with a `paginationTotalHits` default value of 200, and `hitsPerPage` default value of 20, you can browse `paginationTotalHits / hitsPerPage` => `200 / 20 ` => `10` pages during pagination. Each of the 10 pages containing 20 results.<br>
```

2020-11-05 17:30 UTC, bidoubiwa commented on README.md
> +- `paginationTotalHits` (`200` by default): The total (and finite) number of hits you can browse during pagination when using the [pagination widget](https://www.algolia.com/doc/api-reference/widgets
I let you chose the one you prefer:

```suggestion
- `paginationTotalHits` (`200` by default): The total (and finite) number of hits you can browse during pagination when using the [pagination widget](https://www.algolia.com/doc/api-reference/widgets/pagination/js/). If the pagination widget is not used, `paginationTotalHits` is ignored.<br>
```

```suggestion
- `paginationTotalHits` (`200` by default): The total (and finite) number of hits you can browse during pagination when using the [pagination widget](https://www.algolia.com/doc/api-reference/widgets/pagination/js/). If the pagination widget is not added in the options, `paginationTotalHits` is ignored.<br>
```

```suggestion
- `paginationTotalHits` (`200` by default): The total (and finite) number of hits you can browse during pagination when using the [pagination widget](https://www.algolia.com/doc/api-reference/widgets/pagination/js/). If the pagination widget is not added in the configuration, `paginationTotalHits` is ignored.<br>
```

2020-11-09 13:25 UTC, curquiza commented on README.md
> +It means, by default, you can browse `paginationTotalHits / hitsPerPage = 200 / 20 = 10` pages during pagination.<br>
```suggestion
Which means that, with a `paginationTotalHits` default value of 200, and `hitsPerPage` default value of 20, you can browse `paginationTotalHits / hitsPerPage` => `200 / 20 = 10` pages during pagination. Each of the 10 pages containing 20 results.<br>
```

2020-11-09 13:31 UTC, merged