Fix infinite hits
meilisearch/instant-meilisearch pull request #335
Opened 2021-03-15 16:09 UTC by bidoubiwa

Fix `<InfiniteHits />` that did not work without `<Pagination />`

2021-03-15 16:28 UTC, curquiza approved these changes

2021-03-15 16:50 UTC, mdubus approved these changes

2021-03-16 09:14 UTC, curquiza requested changes
Could you fix the `pagination && pagination` line? 😇

2021-03-21 18:38 UTC, curquiza submitted a review, later dismissed

2021-03-23 09:27 UTC, mdubus requested changes

2021-03-23 09:27 UTC, mdubus commented on src/index.ts
> +      const attributesToCrop = attributesToSnippet
If you really want to rename `attributesToSnippet` to `attributesToCrop`, you can do it directly in the deconstruction, and avoid creating a new variable :) 

```js
    transformToMeiliSearchParams: function ({
      query,
      facets,
      facetFilters,
      attributesToSnippet: attributesToCrop,
      attributesToRetrieve,
      attributesToHighlight,
      filters,
    }) {
```

2021-03-24 08:40 UTC, curquiza approved these changes
After the application of the Morgane's comment, I approve 🙂

2021-03-25 16:29 UTC, mdubus approved these changes

2021-03-25 16:50 UTC, bidoubiwa commented
bors merge

2021-03-25 16:54 UTC, curquiza approved these changes

2021-03-25 16:54 UTC, merged