Add compatibility with hierarchicalMenu and breadcrumb in readme
meilisearch/instant-meilisearch pull request #682
Opened 2022-03-02 15:17 UTC by bidoubiwa

Per @gmourier tests, these widgets are compatible provided that you meet the requirements. 
For example the document structure and the settings.

2022-03-02 17:20 UTC, brunoocasali requested changes
I found some typos regarding the English (grammarly did, actually 😝)

2022-03-02 17:20 UTC, brunoocasali commented on README.md
> +The `hierarchicalMenu` widget is used to create a navigation based on a hierarchy of facet attributes. It is commonly used for categories with subcategories. See [usage](#hierarchical-menu-usage) bel
```suggestion
The `hierarchicalMenu` widget is used to create navigation based on a hierarchy of facet attributes. It is commonly used for categories with subcategories. See [usage](#hierarchical-menu-usage) below.
```

2022-03-02 17:20 UTC, brunoocasali commented on README.md
> +- ✅ limit: How many facet values to retrieves.
```suggestion
- ✅ limit: How many facet values to retrieve.
```

2022-03-02 17:20 UTC, brunoocasali commented on README.md
> +To make it work with Meilisearch your documents must have a specific structure, explaination on the structure can [be found here](https://www.algolia.com/doc/api-reference/widgets/hierarchical-menu/j
```suggestion
To make it work with Meilisearch your documents must have a specific structure, an explanation of the structure can [be found here](https://www.algolia.com/doc/api-reference/widgets/hierarchical-menu/js/#requirements).
```

2022-03-02 17:20 UTC, brunoocasali commented on README.md
> +Contrary to `instantsearch.js`, the hierchical fields are added in [`filterableAttributes`](https://docs.meilisearch.com/reference/api/filterable_attributes.html#update-filterable-attributes).
```suggestion
Contrary to `instantsearch.js`, the hierarchical fields are added in [`filterableAttributes`](https://docs.meilisearch.com/reference/api/filterable_attributes.html#update-filterable-attributes).
```

2022-03-02 22:28 UTC, brunoocasali approved these changes
LGTM! 🌮

2022-03-03 08:32 UTC, bidoubiwa commented
bors merge

2022-03-03 09:50 UTC, bidoubiwa commented
bors merge

2022-03-03 09:53 UTC, merged